const PRODUCT = {
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",
  CLEAR_DATA: "CLEAR_DATA",
  SET_STATE_REDUCER: "SET_STATE_REDUCER",
};

const USER = {
  SIGNUP: "USER_SIGNUP",
  SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  SIGNUP_FAIL: "USER_SIGNUP_FAIL",
  SIGNIN: "USER_SIGNIN",
  SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  SIGNIN_FAIL: "USER_SIGNIN_FAIL",
  UPDATE_STATE: "UPDATE_STATE",
  LOGOUT: "USER_LOGOUT",
  LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  LOGOUT_FAIL: "USER_LOGOUT_FAIL",
  GET_MY_INFO: "GET_MY_INFO",
  GET_MY_INFO_SUCCESS: "GET_MY_INFO_SUCCESS",
  GET_MY_INFO_FAIL: "GET_MY_INFO_FAIL",
};

export { PRODUCT, USER };
